version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
  pre_build:
    commands:
      - echo Logging in to DockerHub...
      - echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
  build:
    commands:
      - echo Building Docker image...
      - docker build -t $DOCKERHUB_USERNAME/my-nodejs-app:latest .
  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push $DOCKERHUB_USERNAME/my-nodejs-app:latest
      - echo Build completed successfully!
